_inicio:
    pattern:  /
    defaults: { _controller: LibrariumBundle:Index:index }

_catalogo:
    resource: "@LibrariumBundle/Controller/CatalogController.php"
    type:     annotation
    prefix:   /catalogo
    defaults: { _controller: LibrariumBundle:Catalog:browse }

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator
